version: "3"

services:
  node-app:
    container_name: my-volumeclient
    build: .
    image: fahidnasir/node-upload-volume:1.0
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - data-volume:/var/lib/files/

volumes:
  data-volume:
